# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SkMWH8rcRynHG0ZCNTOg6I5HIM5Bl6Ka
"""

import requests

r = requests.get("https://www.freecodecamp.org/")
print(r.text)

import re

pattern = re.compile(r'<.*?>')
print(pattern.sub('', r.text))

from bs4 import BeautifulSoup

soup = BeautifulSoup(r.text, "html5lib")
print(soup.get_text())

summaries = soup.find_all("div", class_="tex2jax_ignore")
summaries[0]

summaries[0].get_text().strip()

